server:
  port: 8090

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 100
        max-idle: 200
        max-active: 500
        max-wait: 10000
    lettuce:
      shutdown-timeout: 0


